/**
 * 新闻BaseModel
 */
package basemodel;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}
	
	public void setCont(java.lang.String cont) {
		set("cont", cont);
	}

	public java.lang.String getCont() {
		return get("cont");
	}
	
	public void setDate(String date){
		set("date", date);
	}
	
	public String getDate(){
		return get("date");
	}
	
	public void setDatec(java.lang.String datec){
		set("datec", datec);
	}
	
	public java.lang.String getDatec(){
		return get("datec");
	}

	public void setDocPath(java.lang.String docpath){
		set("docpath", docpath);
	}
	
	public java.lang.String getDocPath(){
		return get("docpath");
	}

	public void setPicPath(java.lang.String picpath){
		set("picpath", picpath);
	}
	
	public java.lang.String getPicPath(){
		return get("picpath");
	}	
	
	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return get("author");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}
	
	public void setAuthorId(java.lang.Integer author_id) {
		set("author_id", author_id);
	}

	public java.lang.Integer getAuthorId() {
		return get("author_id");
	}
	
	public void setDay(java.lang.String day) {
		set("day", day);
	}

	public java.lang.String getDay() {
		return get("day");
	}
	
	public void setMonth(java.lang.String month) {
		set("month", month);
	}

	public java.lang.String getMonth() {
		return get("month");
	}
	
	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}
}


