/**
 * BaseModel demo
 */
package basemodel;

import java.util.Date;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSource<M extends BaseSource<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}
	
	public void setDate(Date date){
		set("date", date);
	}
	
	public Date getDate(){
		return get("date");
	}
	
	public void setDatec(java.lang.String datec){
		set("datec", datec);
	}
	
	public java.lang.String getDatec(){
		return get("datec");
	}

	public void setDocPath(java.lang.String docpath){
		set("docpath", docpath);
	}
	
	public java.lang.String getDocPath(){
		return get("docpath");
	}

	public void setPicPath(java.lang.String picpath){
		set("picpath", picpath);
	}
	
	public java.lang.String getPicPath(){
		return get("picpath");
	}	
	
	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return get("author");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}
	
	public void setAuthorId(java.lang.Integer author_id) {
		set("author_id", author_id);
	}

	public java.lang.Integer getAuthorId() {
		return get("author_id");
	}
	
}

