/**
 * 活动模型
 * 主要  关于数据的操作 sql
 */
package model;

import java.util.List;

import basemodel.BaseActive;

import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 * Active model.
 * 数据库字段名建议使用驼峰命名规则，便于与 java 代码保持一致，如字段名： userId
 */
@SuppressWarnings("serial")
public class Active extends BaseActive<Active> {
	
	public static final Active act = new Active();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，
	 * 不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<Active> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from activity order by id desc");
	}
	
	public Page<Active> paginate(int pageNumber, int pageSize, String key) {
		return paginate(pageNumber, pageSize, "select *", "from activity where title like ? order by id desc", "%"+key+"%");
	}
	
	public List<Active> fName(){
		List<Active> fnames ;
		String sql = "select * from activity";
		fnames = Active.act.find(sql);
		return fnames;
	}
	
	public String docPath(int id){
		Active active = Active.act.findById(id);
		return active.getDocPath();
	}
	
	public void countAdd(int id){
		Active a = Active.act.findById(id);
		int count = a.getCount();
		a.setCount(++count);
		a.update();
	}

}


