/**
 * 新闻model
 * 关于 新闻表的操作 sql
 */
package model;

import java.util.List;

import basemodel.BaseNews;

import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 * News model.
 * 数据库字段名建议使用驼峰命名规则，便于与 java 代码保持一致，如字段名： userId
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	
	public static final News news = new News();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，
	 * 不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<News> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from news order by id desc");
	}
	
	public Page<News> paginate(int pageNumber, int pageSize, String key) {
		return paginate(pageNumber, pageSize, "select *", "from news where title like ? order by id desc","%"+key+"%");
	}
	
	public List<News> fName(){
		List<News> fnames ;
		String sql = "select * from news";
		fnames = News.news.find(sql);
		return fnames;
	}

	public String docPath(int id){
		News news = News.news.findById(id);
		return news.getDocPath();
	}
	
	public void countAdd(int id){
		News n = News.news.findById(id);
		int count = n.getCount();
		n.setCount(++count);
		n.update();
	}

}


