/**
 * 资源model
 * demo
 */
package model;

import java.util.List;

import basemodel.BaseSource;

import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 * Source model.
 * 数据库字段名建议使用驼峰命名规则，便于与 java 代码保持一致，如字段名： userId
 */
@SuppressWarnings("serial")
public class Source extends BaseSource<Source> {
	
	public static final Source src = new Source();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，
	 * 不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<Source> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from src order by id asc");
	}
	
	public List<Source> fName(){
		List<Source> fnames ;
		String sql = "select * from src";
		fnames = Source.src.find(sql);
		return fnames;
	}

}


