/**
 * 政策法规model
 * 关于 政策法规表的操作 sql
 */
package model;

import java.util.List;

import basemodel.BaseStatute;

import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 * Statute model.
 * 数据库字段名建议使用驼峰命名规则，便于与 java 代码保持一致，如字段名： userId
 */
@SuppressWarnings("serial")
public class Statute extends BaseStatute<Statute> {
	
	public static final Statute stat = new Statute();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，
	 * 不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<Statute> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from statute order by id desc");
	}
	
	public Page<Statute> paginate(int pageNumber, int pageSize, String key) {
		return paginate(pageNumber, pageSize, "select *", "from statute where title like ? order by id desc", "%"+key+"%");
	}
	
	public List<Statute> fName(){
		List<Statute> fnames ;
		String sql = "select * from statute";
		fnames = Statute.stat.find(sql);
		return fnames;
	}
	
	public String docPath(int id){
		Statute statute = Statute.stat.findById(id);
		return statute.getDocPath();
	}
	
	public void countAdd(int id){
		Statute statute = Statute.stat.findById(id);
		int count = statute.getCount();
		statute.setCount(++count);
		statute.update();
	}
	
	public List<Statute> recommend(){
//		String sql = "SELECT * FROM statute where docpath is not null LIMIT 5;";
		String sql = "SELECT * FROM statute WHERE docpath != \" \" limit 2;";
		List<Statute> sList;
		sList = Statute.stat.find(sql);
		return sList;
	}
	
}


