/**
 * 医院模型
 * 主要  关于数据的操作 sql
 */
package model;

import java.util.List;

import basemodel.BaseSubcenter;

import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 * Active model.
 * 数据库字段名建议使用驼峰命名规则，便于与 java 代码保持一致，如字段名： userId
 */
@SuppressWarnings("serial")
public class Subcenter extends BaseSubcenter<Subcenter> {
	
	public static final Subcenter sbc = new Subcenter();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，
	 * 不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<Subcenter> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from subcenter order by id asc");
	}
	
	// for search
	public Page<Subcenter> paginate(int pageNumber, int pageSize, String key) {
		return paginate(pageNumber, pageSize, "select *", "from subcenter where title like ? order by id asc", "%"+key+"%");
	}
	
	public List<Doctor> fName(){
		List<Doctor> fnames ;
		String sql = "select * from activity";
		fnames = Doctor.doctor.find(sql);
		return fnames;
	}
	
	public String docPath(int id){
		Active active = Active.act.findById(id);
		return active.getDocPath();
	}
	
	public void countAdd(int id){
		Active a = Active.act.findById(id);
		int count = a.getCount();
		a.setCount(++count);
		a.update();
	}

}


